language: r

sudo: required
warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

cache: packages


after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack: huckley:RH9dq9u04SKLALXK6EQa0mkp

env:
  global:
  - CRAN: http://cran.rstudio.com
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
  - R_CHECK_TESTS="FALSE"
