language: r
sudo: true
cache: packages


after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
  on_success: never
on_failure: never
slack: huckley:RH9dq9u04SKLALXK6EQa0mkp

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
  - _R_CHECK_TIMINGS_="0"
  - R_CHECK_TESTS="FALSE"
